### ISSUE TITLE
GODOT_SUBCLASS macro: "no suitable constructor exists"

### ISSUE THREAD

**Issue by willnationsdev** [GodotNativeTools/cpp_bindings#13]
**Context**
Windows 10
Visual Studio 2015 Community Edition

**Issue:**
when using GODOT_SUBCLASS(NewNode, Node), the line below gives the following error:

`inline NewNode(godot_object *o) : Node(o) {}` (from cpp_bindings/include/core/Godot.hpp: line 58)

"no suitable constructor exists to convert from "godot_object *" to "godot::Node"

I arrived at this error while attempting to follow through the Player : KinematicBody2D example in the "GDNative is here!" article. Simplifying it to just extending a similar class NewNode from godot::Node caused the same error.

I understand if this isn't something that needs to be addressed at all since this stuff is still in development, technically. Just thought I'd bring it up in case it was unexpected / worthy of attention.

**Comment by karroffel** [comment]
You're not supposed to use it that way. GODOT_SUBCLASS is to inherit from *another* GDNative script, just like `extends "res://some_class.gd"` in GDScript.

See the example in the README to inherit from Node. Just substitute `Reference` by `Node`

**Comment by willnationsdev** [comment]
Ah, I see. Yeah, just tested it and its' compiling fine with that setup. Thanks.
