### ISSUE TITLE
Path to Godot executable

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotNativeTools/cpp_bindings#15]
Just nitpicking but the path is set twice:
https://github.com/GodotNativeTools/cpp_bindings/blob/master/SConstruct#L7
and
https://github.com/GodotNativeTools/cpp_bindings/blob/master/SConstruct#L10

But the real issue, it would be nice if this is somehow configurable, maybe an argument?

**Comment by BastiaanOlij** [comment]
ah never mind, bin path vs lib path ;)

**Comment by karroffel** [comment]
Hehe 😄
