### ISSUE TITLE
`const` methods cannot be registered

### ISSUE THREAD

**Issue by Zylann** [GodotNativeTools/cpp_bindings#6]
Godot 3.0 pre-alpha master
Windows 10 64 bits MSVC

When making a GDNative library using the C++ kit, I figured out C++ functions declared as const produce compilation errors when used in method bindings. As a result, none can be declared as such (mostly getters, calculations and things that should be guaranteed to be read-only). This is supported when making a module, I expected it to work in GDNative too.

My current workaround is a `#define ZCONST` that I use like`const` instead, except it's empty so nothing is actually const (and will replace it with `const` again once this is fixed^^)

**Comment by karroffel** [comment]
I guess there's a difference between `R (T::*p)(args..)` and `R (T::*p)(args..) const` (maybe?!) Will look into that 😄
