### ISSUE TITLE
Can't generate bindings

### ISSUE THREAD

**Issue by JimmyJames707** [GodotNativeTools/cpp_bindings#9]
I downloaded a version of Godot from here:
http://fixnum.org/godot/#latest_complete

And followed your instructions to generate the cpp bindings up to this point:
`
scons p=linux target=bindings generate_bindings=yes`

But get the following errors:

scons: Reading SConscript files ...
GLES3: max extensions: 356
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ERROR: set_method_flags: Condition ' !check->method_map.has(p_method) ' is true.
   At: core/class_db.cpp:1008.
ERROR: set_method_flags: Condition ' !check->method_map.has(p_method) ' is true.
   At: core/class_db.cpp:1008.
ERROR: set_method_flags: Condition ' !check->method_map.has(p_method) ' is true.
   At: core/class_db.cpp:1008.
ERROR: set_method_flags: Condition ' !check->method_map.has(p_method) ' is true.
   At: core/class_db.cpp:1008.
mesege
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Performance	ID: 131218	Severity: Medium	Message: Program/shader state performance warning: Vertex shader in program 1 is being recompiled based on GL state.
   At: drivers/gles3/rasterizer_gles3.cpp:123.
ERROR: load: No loader found for resource: res://godot_api.json
   At: core/io/resource_loader.cpp:213.
ERROR: start: Failed loading scene: res://godot_api.json
   At: main/main.cpp:1462.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1910.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/dvector.cpp:69.
IOError: [Errno 2] No such file or directory: 'godot_api.json':
  File "/home/pc/Applications/Godot/Godot3.0/SimpleLibrary/cpp_bindings/SConstruct", line 71:
    binding_generator.generate_bindings(json_api_file)
  File "/home/pc/Applications/Godot/Godot3.0/SimpleLibrary/cpp_bindings/binding_generator.py", line 9:
    classes = json.load(open(path))

**Comment by karroffel** [comment]
Did you download a tool build?
Are you on Linux?

**Comment by JimmyJames707** [comment]
I downloaded this one:
http://fixnum.org/godot/17_05_19__20_21_33/tools/godot.x11.tools.64

 I am on Manjaro, which is Arch. 

Are you using one from the above list? If so perhaps I should use the date you are using.

**Comment by karroffel** [comment]
I'm compiling Godot myself - always.

So this might be a problem with an outdated version of fixnum builds

**Comment by JimmyJames707** [comment]
Okay I just built Godot on this machine. It gets a lot further, but I have the same problem with this command:
scons p=linux target=bindings generate_bindings=yes

scons: Reading SConscript files ...
GLES3: max extensions: 356
hdr supported: 1
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
mesege
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Performance	ID: 131218	Severity: Medium	Message: Program/shader state performance warning: Vertex shader in program 1 is being recompiled based on GL state.
   At: drivers/gles3/rasterizer_gles3.cpp:123.
ERROR: load: No loader found for resource: res://cpp_bindings/godot_api.json
   At: core/io/resource_loader.cpp:213.
ERROR: start: Failed loading scene: res://cpp_bindings/godot_api.json
   At: main/main.cpp:1462.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1910.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/dvector.cpp:69.
scons: done reading SConscript files.
scons: Building targets ...
g++ -o src/CollisionPolygon.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/CollisionPolygon.cpp
g++ -o src/VisualScriptIterator.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/VisualScriptIterator.cpp
g++ -o src/TextureButton.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/TextureButton.cpp
g++ -o src/ConcavePolygonShape2D.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/ConcavePolygonShape2D.cpp
g++ -o src/ProgressBar.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/ProgressBar.cpp
g++ -o src/OptionButton.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/OptionButton.cpp
g++ -o src/OccluderPolygon2D.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/OccluderPolygon2D.cpp
g++ -o src/VisualScriptConstant.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/VisualScriptConstant.cpp
g++ -o src/LineShape2D.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/LineShape2D.cpp
g++ -o src/Shape.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/Shape.cpp
g++ -o src/SpinBox.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/SpinBox.cpp
g++ -o src/ColorRect.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/ColorRect.cpp
g++ -o src/CanvasModulate.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/CanvasModulate.cpp
g++ -o src/ConfirmationDialog.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/ConfirmationDialog.cpp
g++ -o src/Tree.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/Tree.cpp
g++ -o src/Position3D.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/Position3D.cpp
g++ -o src/TCP_Server.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/TCP_Server.cpp
g++ -o src/Panel.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/Panel.cpp
g++ -o src/PhysicsDirectBodyStateSW.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/PhysicsDirectBodyStateSW.cpp
g++ -o src/TouchScreenButton.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/TouchScreenButton.cpp
g++ -o src/VisualScriptSceneTree.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/VisualScriptSceneTree.cpp
g++ -o src/StyleBoxFlat.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/StyleBoxFlat.cpp
g++ -o src/AudioServer.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/AudioServer.cpp
g++ -o src/VisualScriptNode.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/VisualScriptNode.cpp
g++ -o src/RayShape2D.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/RayShape2D.cpp
g++ -o src/PackedScene.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/PackedScene.cpp
g++ -o src/VisualScriptExpression.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/VisualScriptExpression.cpp
g++ -o src/ReflectionProbe.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/ReflectionProbe.cpp
g++ -o src/AudioEffectPitchShift.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/AudioEffectPitchShift.cpp
g++ -o src/ConeTwistJoint.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/ConeTwistJoint.cpp
g++ -o src/AnimationPlayer.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/AnimationPlayer.cpp
g++ -o src/SphereShape.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/SphereShape.cpp
g++ -o src/Camera.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/Camera.cpp
g++ -o src/ShortCut.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/ShortCut.cpp
g++ -o src/StreamTexture.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/StreamTexture.cpp
g++ -o src/Directory.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/Directory.cpp
g++ -o src/ColorPickerButton.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/ColorPickerButton.cpp
g++ -o src/ViewportTexture.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/ViewportTexture.cpp
g++ -o src/StreamPeer.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/StreamPeer.cpp
g++ -o src/VisualScriptSequence.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/VisualScriptSequence.cpp
g++ -o src/AudioEffectAmplify.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/AudioEffectAmplify.cpp
g++ -o src/ConvexPolygonShape2D.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/ConvexPolygonShape2D.cpp
g++ -o src/Node2D.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/Node2D.cpp
g++ -o src/ResourceLoader.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/ResourceLoader.cpp
g++ -o src/HSplitContainer.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/HSplitContainer.cpp
g++ -o src/VisualScriptCondition.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/VisualScriptCondition.cpp
g++ -o src/Node.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/Node.cpp
g++ -o src/AudioStreamPlayback.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/AudioStreamPlayback.cpp
g++ -o src/SceneTreeTimer.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/SceneTreeTimer.cpp
g++ -o src/Particles2D.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/GDNative/SimpleLibrary/godot_headers -Iinclude -Iinclude/core src/Particles2D.cpp
src/Particles2D.cpp:12:25: fatal error: ColorRamp.hpp: No such file or directory
 #include <ColorRamp.hpp>
                         ^
compilation terminated.
scons: *** [src/Particles2D.os] Error 1
scons: building terminated because of errors.

**Comment by JimmyJames707** [comment]
Any ideas what might be wrong? It seems to be missing ColorRamp.hpp. Is there something missing that is needed to handle that?

**Comment by karroffel** [comment]
That's really weird. It should generate that file. It compiles for me, looks like your api.json generated from Godot is weird or something.

Is there the file `include/ColorRamp.hpp` for you?

**Comment by JimmyJames707** [comment]
>Is there the file include/ColorRamp.hpp for you?

No, there is no such file. 

cpp_bindings/include/core has files in it. cpp_bindings/include/ is empty.

**Comment by JimmyJames707** [comment]
Opps, I must have deleted it and downloaded it again.

I just ran those commands again. The include directory has files in it, but there is no ColorRamp.hpp. There are 412 files in it.

**Comment by karroffel** [comment]
Interesting, I can now reproduce. This is an upstream error though, I'll see if I can make a patch for Godot.

Looking into it ;)

**Comment by gtsiam** [comment]
From what I can gather, the problem seems to be with the Gradient class in Godot not deciding whether it wants to be called Gradient or ColorRamp. So, if that really is all there is to it, could you please hurry with the fix? Because I cant use the c++ bindings until then, and I imagine many others have the same problem (ie everyone at this point in time) - so... Bump...

**Comment by karroffel** [comment]
@gtsiam just opened a PR [here](https://github.com/godotengine/godot/pull/9160)

> So, if that really is all there is to it, could you please hurry with the fix?

But damn, chill 😄 These bindings are still subject to change, so don't really rely on them. Nice to see you needing them though 😄 

What are you using them for though? Just interested to hear ^^

**Comment by karroffel** [comment]
Okay, should now build fine!

**Comment by gtsiam** [comment]
Nice, thanks! I just want to experiment with a couple of procedural generation ideas, previously limited by GDScript's performance. Did not mean for it to look like I was so dependent on the bindings that I needed a fix right there and then (at least, not yet :smile:). But hey, no harm done!

**Comment by JimmyJames707** [comment]
There are a lot of people excited about GDScript. Thanks for your efforts karroffel! :)

**Comment by JimmyJames707** [comment]
Okay I had time to try again. I downloaded and built Godot + downloaded latest GDNative, but it gets stuck again. Oh well. lol

$ scons p=linux target=bindings generate_bindings=yes
scons: Reading SConscript files ...
GLES3: max extensions: 356
hdr supported: 1
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ERROR: add_property: Invalid Setter: Environment::set_ssr_accel for property: ss_reflections_accel
   At: core/class_db.cpp:763.
mesege
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Performance	ID: 131218	Severity: Medium	Message: Program/shader state performance warning: Vertex shader in program 1 is being recompiled based on GL state.
   At: drivers/gles3/rasterizer_gles3.cpp:123.
ERROR: load: No loader found for resource: res://godot_api.json
   At: core/io/resource_loader.cpp:213.
ERROR: start: Failed loading scene: res://godot_api.json
   At: main/main.cpp:1461.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1910.
scons: done reading SConscript files.
scons: Building targets ...
g++ -o src/CollisionPolygon.os -c -Wno-write-strings -Wno-return-local-addr -g -O3 -std=c++14 -fPIC -D_GD_CPP_BINDING_IMPL -I. -I/home/pc/Applications/Godot/Git/GDNativeTools/godot_headers -Iinclude -Iinclude/core src/CollisionPolygon.cpp
In file included from src/CollisionPolygon.cpp:5:0:
include/core/Godot.hpp: In static member function 'static T godot::_ArgCast<T>::_arg_cast(godot::Variant)':
include/core/Godot.hpp:69:21: error: 'class godot::Variant' has no member named 'operator T'; did you mean 'operator unsigned int'?
   return a.operator T();
                     ^
                     operator 11
scons: *** [src/CollisionPolygon.os] Error 1
scons: building terminated because of errors.

**Comment by karroffel** [comment]
@JimmyJames707 Can you try building with clang? `use_llvm=yes`

**Comment by JimmyJames707** [comment]
I got this:

 scons p=linux target=bindings generate_bindings=yes use_llvm=yes
scons: Reading SConscript files ...
OSError: [Errno 2] No such file or directory:
  File "/home/pc/Applications/Godot/Git/GDNativeTools/cpp_bindings/SConstruct", line 69:
    subprocess.call([godot_executable, '--gdnative-generate-json-api', json_api_file])
  File "/usr/lib/python2.7/subprocess.py", line 168:
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 390:
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024:
    raise child_exception

**Comment by karroffel** [comment]
@JimmyJames707 Huge patch incoming, should fix everything :)
